name: Merge Feature into Environment branch

on:
  workflow_run:
    workflows: ['Release']
    types:
      - completed
    branches-ignore:
      - main
      - master
      - env/*

jobs:
  merge_feature_into_env:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.workflow_run.head_commit.message, '[rc]') && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Fetch env branch
        run: git fetch origin env/staging1:env/staging1 --unshallow

      - name: Checkout env branch
        run: git checkout env/staging1

      - name: Merge feature branch into env branch
        run: |
          git merge ${{ github.event.workflow_run.head_branch }} -m "feat(auto): Merge branch '${{ github.event.workflow_run.head_branch }}' into 'env/staging1'"

      - name: Push changes to rc branch
        run: git push origin env/staging1

      - name: Notify if conflicts detected
        if: failure()
        run: echo "Merge conflict detected. Manual resolution required."