name: Merge Master into Environment branch

on: 
  push:
    branches:
      - main
      - master

jobs:
  merge_master_into_rc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Fetch env branch
        run: git fetch origin env/staging1:env/staging1 --unshallow

      - name: Checkout env branch
        run: git checkout env/staging1

      - name: Merge master into env branch
        run: 'git merge master -m "fix(auto): Merge master back to env"'

      - name: Push changes to env branch
        run: git push origin env/staging1

      - name: Notify if conflicts detected
        if: failure()
        run: echo "Merge conflict detected. Manual resolution required."
