name: Release 

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

  update_env_branch:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ contains(github.event.head_commit.message, '[rc]') || github.ref_name == 'main' }}
    continue-on-error: true
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Fetch env branch
        run: git fetch origin env/staging1:env/staging1 --unshallow

      - name: Checkout env branch
        run: git checkout env/staging1

      - name: Merge current branch into env branch
        run: |
          git merge ${{ github.ref_name }} -m "fix(auto): Merge '${{ github.ref_name }}' into 'env/staging1'"

      - name: Push changes to env branch
        run: git push origin env/staging1

      - name: Notify if conflicts detected
        if: failure()
        run: echo "Merge conflict detected. Manual resolution required."
