name: Reset environment branch 

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  reset_env_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Fetch env branch
        run: git fetch origin env/staging1:env/staging1 --unshallow

      - name: Checkout env branch
        run: git checkout env/staging1

      - name: Reset current branch to master
        run: git reset --hard master

      - name: Push changes to env branch
        run: git push origin env/staging1 --force

      - name: Notify if conflicts detected
        if: failure()
        run: echo "Merge conflict detected. Manual resolution required."
